# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_contact.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 308)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/system-users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.insert_contact = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insert_contact.setIcon(icon1)
        self.insert_contact.setObjectName("insert_contact")
        self.gridLayout.addWidget(self.insert_contact, 1, 1, 1, 1)
        self.esci = QtWidgets.QPushButton(Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/dialog-close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.esci.setIcon(icon2)
        self.esci.setObjectName("esci")
        self.gridLayout.addWidget(self.esci, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.email = QtWidgets.QLineEdit(self.groupBox)
        self.email.setObjectName("email")
        self.gridLayout_2.addWidget(self.email, 3, 1, 1, 1)
        self.name = QtWidgets.QLineEdit(self.groupBox)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.surname = QtWidgets.QLineEdit(self.groupBox)
        self.surname.setObjectName("surname")
        self.gridLayout_2.addWidget(self.surname, 1, 1, 1, 1)
        self.phone = QtWidgets.QLineEdit(self.groupBox)
        self.phone.setObjectName("phone")
        self.gridLayout_2.addWidget(self.phone, 4, 1, 1, 1)
        self.address = QtWidgets.QLineEdit(self.groupBox)
        self.address.setObjectName("address")
        self.gridLayout_2.addWidget(self.address, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.mobile = QtWidgets.QLineEdit(self.groupBox)
        self.mobile.setObjectName("mobile")
        self.gridLayout_2.addWidget(self.mobile, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.name, self.surname)
        Dialog.setTabOrder(self.surname, self.address)
        Dialog.setTabOrder(self.address, self.email)
        Dialog.setTabOrder(self.email, self.phone)
        Dialog.setTabOrder(self.phone, self.mobile)
        Dialog.setTabOrder(self.mobile, self.insert_contact)
        Dialog.setTabOrder(self.insert_contact, self.esci)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Insert contact"))
        self.insert_contact.setText(_translate("Dialog", "Insert"))
        self.esci.setText(_translate("Dialog", "Close"))
        self.groupBox.setTitle(_translate("Dialog", "Save new contact"))
        self.label_4.setText(_translate("Dialog", "Email"))
        self.label.setText(_translate("Dialog", "Name*"))
        self.label_3.setText(_translate("Dialog", "Address"))
        self.label_5.setText(_translate("Dialog", "Phone"))
        self.label_2.setText(_translate("Dialog", "Surname*"))
        self.label_6.setText(_translate("Dialog", "Mobile*"))

import rubrica_rc
