# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rubrica.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(229, 331)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/system-users.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.about_contact = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_contact.setIcon(icon1)
        self.about_contact.setObjectName("about_contact")
        self.gridLayout_2.addWidget(self.about_contact, 5, 0, 1, 1)
        self.remove_contatct = QtWidgets.QPushButton(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_contatct.setIcon(icon2)
        self.remove_contatct.setObjectName("remove_contatct")
        self.gridLayout_2.addWidget(self.remove_contatct, 2, 0, 1, 1)
        self.find_contact = QtWidgets.QPushButton(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/edit-find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.find_contact.setIcon(icon3)
        self.find_contact.setObjectName("find_contact")
        self.gridLayout_2.addWidget(self.find_contact, 4, 0, 1, 1)
        self.update_contatc = QtWidgets.QPushButton(self.groupBox)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/system-software-update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.update_contatc.setIcon(icon4)
        self.update_contatc.setObjectName("update_contatc")
        self.gridLayout_2.addWidget(self.update_contatc, 3, 0, 1, 1)
        self.addContact = QtWidgets.QPushButton(self.groupBox)
        self.addContact.setIcon(icon)
        self.addContact.setObjectName("addContact")
        self.gridLayout_2.addWidget(self.addContact, 1, 0, 1, 1)
        self.view_contact = QtWidgets.QPushButton(self.groupBox)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/view_contact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_contact.setIcon(icon5)
        self.view_contact.setObjectName("view_contact")
        self.gridLayout_2.addWidget(self.view_contact, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 229, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setObjectName("actionExit")
        self.actionInsert = QtWidgets.QAction(MainWindow)
        self.actionInsert.setIcon(icon)
        self.actionInsert.setObjectName("actionInsert")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setIcon(icon2)
        self.actionRemove.setObjectName("actionRemove")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setIcon(icon4)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFind_contact = QtWidgets.QAction(MainWindow)
        self.actionFind_contact.setIcon(icon3)
        self.actionFind_contact.setObjectName("actionFind_contact")
        self.actionView_contact = QtWidgets.QAction(MainWindow)
        self.actionView_contact.setIcon(icon5)
        self.actionView_contact.setObjectName("actionView_contact")
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionView_contact)
        self.menuEdit.addAction(self.actionInsert)
        self.menuEdit.addAction(self.actionRemove)
        self.menuEdit.addAction(self.actionUpdate)
        self.menuEdit.addAction(self.actionFind_contact)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Address book"))
        self.about_contact.setText(_translate("MainWindow", "About"))
        self.remove_contatct.setText(_translate("MainWindow", "Remove contact"))
        self.find_contact.setText(_translate("MainWindow", "Find contact"))
        self.update_contatc.setText(_translate("MainWindow", "Update contact"))
        self.addContact.setText(_translate("MainWindow", "Add contact"))
        self.view_contact.setText(_translate("MainWindow", "View contact"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionInsert.setText(_translate("MainWindow", "Add contact"))
        self.actionRemove.setText(_translate("MainWindow", "Remove contact"))
        self.actionUpdate.setText(_translate("MainWindow", "Update contact"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionFind_contact.setText(_translate("MainWindow", "Find contact"))
        self.actionView_contact.setText(_translate("MainWindow", "View contact"))

import rubrica_rc
